### ISSUE TITLE
Crash - CreateInterface FATAL

### ISSUE THREAD

**Issue by NanoC4t** [Snorflake/Onion#2]
http://i.imgur.com/ZWq3dJ9.png

I believe some p2c is using your code but I can't verify since I'm unable to inject.

**Comment by Snorflake** [comment]
I have released this as open-source, so anyone can use my code for anything
they want. I appreciate the concern but there is nothing I can do.

**Comment by NanoC4t** [comment]
The problem is that he has a few pros under his belt and I am pretty sure he's using what you released:
https://github.com/Snorflake/Onion
https://github.com/Snorflake/csgoradar

Please help me out with this. The radar works fine but the onion one just keeps crashing.

**Comment by Snorflake** [comment]
it's probably the offsets. also, by the nature of the MIT license, they are
free to do what they want with it. read more over here
https://choosealicense.com/licenses/mit/

**Comment by NanoC4t** [comment]
Well it's a bit more complicated. I'm sure he's using your source code but as it stands he's using it as a way to claim he has coding expertise and is now ripping people 1000$ for another game based on this 'Onion' framework. If you can update this thing I can easily compare and hopefully stop people getting scammed by him.
I already have his details, I just need confirmation so he can be blacklisted for what he has done to others.

I am willing to donate to you if you leave a BTC address as a gesture for cooperating with me here.

**Comment by Snorflake** [comment]
no, thanks.
